---
global:
  domainName: cytomine.local

postgresql:
  storageClassName:
pims:
  imageStorage:
    storageClassName:
  tempImageStorage:
    storageClassName:
  datasetImportFolder: /data/dataset
  datasetImportStorage:
    hostPath:
      path: /data/dataset
      type: DirectoryOrCreate
mongodb:
  storageClassName:
app_engine:
  tasks_namespace:

gateway:
  className: envoy-gateway

iam:
  lsaaiClientIdSecretName:
  lsaaiClientSecretSecretName:
  lsaaiEndpoint:

images:
  imagePullSecretsNames:
    - docker-image-pull-secrets
