services:
  web-ui:
    image: cytomine/web-ui:latest
    build:
      context: ./web-ui/

  pims:
    image: cytomine/pims:latest
    build:
      context: ./
      dockerfile: ./pims/Dockerfile

  iam:
    image: cytomine/iam:latest
    build:
      context: ./iam/

  app-engine:
    image: cytomine/app-engine:latest
    build:
      context: ./
      dockerfile: ./app-engine/Dockerfile

  core:
    image: cytomine/core:latest
    build:
      context: ./
      dockerfile: ./core/Dockerfile

  cbir:
    image: cytomine/cbir:latest
    build:
      context: ./cbir/

  sam:
    image: cytomine/sam:latest
    build:
      context: ./sam/

  nginx:
    image: cytomine/nginx:latest
    build:
      context: ./nginx/

  repository:
    image: cytomine/repository:latest
    build:
      context: ./
      dockerfile: ./repository/Dockerfile
