--liquibase formatted sql
--changeset cytomine:2026-07-20-configuration-id-sequence
ALTER TABLE configuration ALTER COLUMN id DROP DEFAULT;
ALTER TABLE configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('configuration', 'id'), COALESCE((SELECT MAX(id) FROM configuration), 0) + 1, false);
