--liquibase formatted sql

--changeset cytomine:2026-04-08-term-relation-id-identity
ALTER TABLE relation_term ALTER COLUMN id DROP DEFAULT;
ALTER TABLE relation_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('relation_term', 'id'), COALESCE((SELECT MAX(id) FROM relation_term), 0) + 1, false);

