--liquibase formatted sql

--changeset cytomine:2026-04-13-annotation-term-id-identity
ALTER TABLE annotation_term ALTER COLUMN id DROP DEFAULT;
ALTER TABLE annotation_term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('annotation_term', 'id'), COALESCE((SELECT MAX(id) FROM annotation_term), 0) + 1, false);
