--liquibase formatted sql
--changeset cytomine:2026-06-24-tag-domain-association
ALTER TABLE tag_domain_association ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tag_domain_association ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tag_domain_association', 'id'), COALESCE((SELECT MAX(id) FROM tag_domain_association), 0) + 1, false);
ALTER TABLE tag_domain_association RENAME COLUMN domain_ident TO domain_id;
