--liquibase formatted sql
--changeset cytomine:2026-07-06-user-id-sequence
ALTER TABLE sec_user ALTER COLUMN id DROP DEFAULT;
ALTER TABLE sec_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sec_user', 'id'), COALESCE((SELECT MAX(id) FROM sec_user), 0) + 1, false);
