--liquibase formatted sql

--changeset cytomine:2026-04-10-relation-id-identity
ALTER TABLE relation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE relation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('relation', 'id'), COALESCE((SELECT MAX(id) FROM relation), 0) + 1, false);
