--liquibase formatted sql
--changeset cytomine:2026-06-15-storage-id-sequence
ALTER TABLE storage ALTER COLUMN id DROP DEFAULT;
ALTER TABLE storage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('storage', 'id'), COALESCE((SELECT MAX(id) FROM storage), 0) + 1, false);
