--liquibase formatted sql

--changeset cytomine:2026-04-13-reviewed-annotation-id-identity
ALTER TABLE reviewed_annotation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE reviewed_annotation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('reviewed_annotation', 'id'), COALESCE((SELECT MAX(id) FROM reviewed_annotation), 0) + 1, false);
