--liquibase formatted sql

--changeset cytomine:2026-03-16-term-id-identity
ALTER TABLE term ALTER COLUMN id DROP DEFAULT;
ALTER TABLE term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('term', 'id'), COALESCE((SELECT MAX(id) FROM term), 0) + 1, false);
