--liquibase formatted sql
--changeset cytomine:2026-10-01-project-id-sequence
ALTER TABLE project ALTER COLUMN id DROP DEFAULT;
ALTER TABLE project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('project', 'id'), COALESCE((SELECT MAX(id) FROM project), 0) + 1, false);
