--liquibase formatted sql
--changeset cytomine:2026-07-09-sec-user-sec-role-id-sequence
ALTER TABLE sec_user_sec_role ALTER COLUMN id DROP DEFAULT;
ALTER TABLE sec_user_sec_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('sec_user_sec_role', 'id'), COALESCE((SELECT MAX(id) FROM sec_user_sec_role), 0) + 1, false);
