--liquibase formatted sql
ALTER TABLE ontology ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ontology ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('ontology', 'id'), COALESCE((SELECT MAX(id) FROM ontology), 0) + 1, false);
