--liquibase formatted sql
--changeset cytomine:2026-07-15-tag-id-sequence
ALTER TABLE tag ALTER COLUMN id DROP DEFAULT;
ALTER TABLE tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('tag', 'id'), COALESCE((SELECT MAX(id) FROM tag), 0) + 1, false);
