--liquibase formatted sql
--changeset cytomine:2026-06-18-uploaded-file-id-sequence
ALTER TABLE uploaded_file ALTER COLUMN id DROP DEFAULT;
ALTER TABLE uploaded_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('uploaded_file', 'id'), COALESCE((SELECT MAX(id) FROM uploaded_file), 0) + 1, false);
