
ALTER TABLE user_annotation ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_annotation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('user_annotation', 'id'), COALESCE((SELECT MAX(id) FROM user_annotation), 0) + 1, false);
