apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-config
  labels:
    app: iam-config
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
