apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: local-pool
spec:
  blocks:
    - cidr: "172.16.238.100/32"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^eth.*
