{{ if .Values.mongodb.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "mongodb-secret") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $secret := (get $secretData "password") | default (randAlphaNum 64 | b64enc) }}
  password: {{ $secret | quote }}
{{ end }}
