package be.cytomine.common.repository.model.command;

public enum CommandType {
    DELETE_ANNOTATION_TERM_COMMAND,
    DELETE_REVIEWED_ANNOTATION_COMMAND,
    DELETE_TERM_COMMAND,
    DELETE_TERM_RELATION_COMMAND,
    DELETE_USER_ANNOTATION_COMMAND,

    INSERT_ANNOTATION_TERM_COMMAND,
    INSERT_REVIEWED_ANNOTATION_COMMAND,
    INSERT_TERM_COMMAND,
    INSERT_TERM_RELATION_COMMAND,
    INSERT_USER_ANNOTATION_COMMAND,

    UPDATE_REVIEWED_ANNOTATION_COMMAND,
    UPDATE_TERM_COMMAND,
    UPDATE_TERM_RELATION_COMMAND,
    UPDATE_USER_ANNOTATION_COMMAND,
}
