package be.cytomine.common.repository.model.command;

public enum CommandType {
    DELETE_TERM_COMMAND, INSERT_TERM_COMMAND, UPDATE_TERM_COMMAND, DELETE_TERM_RELATION_COMMAND,
    INSERT_TERM_RELATION_COMMAND, UPDATE_TERM_RELATION_COMMAND, DELETE_ONTOLOGY_COMMAND, INSERT_ONTOLOGY_COMMAND,
    UPDATE_ONTOLOGY_COMMAND,
    DELETE_STORAGE_COMMAND, INSERT_STORAGE_COMMAND, UPDATE_STORAGE_COMMAND,
}
