services:

  mongo:
    image: cytomine/mongo:latest
    build:
      context: ../mongo
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/mongo:/data/db
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.2

  postgis:
    image: cytomine/postgis:latest
    build:
      context: ../postgis
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/postgis/data:/var/lib/postgresql/data
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.3

  pims-cache:
    image: redis:7.2
    restart: unless-stopped
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.4

  pims:
    image: cytomine/pims:latest
    build:
      context: ../pims
      dockerfile: docker/backend.dockerfile
    restart: unless-stopped
    depends_on:
      - nginx
      - pims-cache
    volumes:
      - ${AAA_CONFIG_DATASET_PATH}:/${CONTAINER_PATHS_DATASET}
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/images:${CONTAINER_PATHS_IMAGES}
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.5

  core:
    image: cytomine/core:latest
    build:
      context: ../core
    restart: unless-stopped
    depends_on:
      - nginx
      - postgis
      - mongo
      - iam
      - app-engine
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.6

  web_ui:
    image: cytomine/web-ui:latest
    build:
      context: ../web-ui
      dockerfile: ui/docker/Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.7

  nginx:
    image: cytomine/nginx:latest
    build:
      context: ../nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.8

  app-engine:
    image: cytomine/app-engine:latest
    build:
      context: ../app-engine
    restart: unless-stopped
    depends_on:
      - registry
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/app-engine:/data
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.9

  registry:
    image: registry:2.8.3
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/registry:/data
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.10

  iam:
    image: cytomine/iam:latest
    build:
      context: ../iam
      dockerfile: Dockerfile
      target: ci
    restart: unless-stopped
    depends_on:
      - nginx
      - postgis
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.11

  redis:
    image: redis:7.2
    command: --port 6380
    restart: unless-stopped
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/redis:/data
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.12

  cbir:
    image: cytomine/cbir:latest
    build:
      context: ../cbir
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ${AAA_CONFIG_PROJECT_DATA_PATH}/cbir:${CONTAINER_PATHS_CBIR_DATA}
      - ${AAA_CONFIG_WEIGHT_PATH}:/weights
    networks:
      cytomine-network:
        ipv4_address: 172.18.0.13

networks:
  cytomine-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16