services:

  app-engine:
    image: cytomine/app-engine:dev-latest
    build:
      context: ./app-engine
      target: dev-server
    working_dir: "/app"
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    ports:
      - "${DEV_AE_PORT:-8081}:8080"
      - "${DEV_SSH_UI_PORT:-10023}:22"
    volumes:
      - ./app-engine:/app/app-engine
      - ./registry-client:/app/registry-client
      - ./settings.gradle:/app/settings.gradle
      # gradle cache for faster build
      - ./cache/app-engine:/.gradle
    environment:
      GRADLE_USER_HOME: /.gradle

  postgis:
    ports:
      - "${DEV_POSTGIS_PORT:-5432}:5432"

  registry:
    ports:
      - "${DEV_REGISTRY_PORT:-5051}:5000"
