services:

  pims:
    image: cytomine/pims:dev-latest
    build:
      context: ./
      dockerfile: ./pims/Dockerfile
      target: dev-server
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - ./pims:/app
    environment:
      DEBUG: true
      WEB_CONCURRENCY: 1 # only one process in dev

  pims-cache:
    ports:
      - "${DEV_PORT_REDIS:-6379}:6379"
