services:

  app-engine:
    image: cytomine/app-engine:dev-latest
    build:
      context: ./app-engine
      target: dev-server
    working_dir: "/app"
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - ./app-engine:/app/app-engine
      - ./registry-client:/app/registry-client
      - ./settings.gradle:/app/settings.gradle
      # gradle cache for faster build
      - ./cache/app-engine:/.gradle
    environment:
      GRADLE_USER_HOME: /.gradle
