global:
  domainName: 'cytomine.local'

postgresql:
  storageClassName: 'local-path'
pims:
  imageStorage:
    storageClassName: 'local-path'
  tempImageStorage:
    storageClassName: 'local-path'
mongodb:
  storageClassName: 'local-path'
app_engine:
  tasks_namespace:

gateway:
  className: cilium

iam:
  lsaaiClientIdSecretName: lsaai-client-id
  lsaaiClientSecretSecretName: lsaai-client-secret
  lsaaiEndpoint: https://login.aai.lifescience-ri.eu/oidc/.well-known/openid-configuration

images:
  pullPolicy: IfNotPresent

test:
  ingressIP: "172.16.238.100"
