apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam
  labels:
    app: sam
spec:
  progressDeadlineSeconds: 1200
  replicas: 1
  selector:
    matchLabels:
      app: sam
  template:
    metadata:
      labels:
        app: sam
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/sam/sam-config.yaml") . | sha256sum }}"
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      volumes:
        - name: temp
          emptyDir: {}
        - name: sam-cache
          emptyDir: {}
      containers:
      -   name: sam
          securityContext:
          {{- include "cytomine.containerSecurityContext" . | nindent 14 }}
          image: "{{ .Values.images.sam }}"
          ports:
          - containerPort: {{ .Values.sam.port }}
          envFrom:
          - configMapRef:
              name: sam
          command: ["/bin/sh", "-c"]
          args: [ "fastapi run app/main.py"]
          volumeMounts:
            - name: temp
              mountPath: /tmp
            - name: sam-cache
              mountPath: /.cache
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.sam.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.sam.port }}
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.sam.port }}
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
