apiVersion: v1
kind: ConfigMap
metadata:
  name: app-engine
data:
  DB_USERNAME: appengine
  DB_NAME: appengine
  DB_HOST: postgres-app-engine.{{ .Release.Namespace }}.svc.cluster.local
  DB_PORT: "5432"
  API_PREFIX: /api/
  REGISTRY_URL: http://registry.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.app_engine.registry.port }}
  SCHEDULER_ADVERTISED_URL: http://app-engine.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.app_engine.port }}
  SCHEDULER_REGISTRY_ADVERTISED_URL: {{ .Values.app_engine.registry.advertisedUrl | default (printf "localhost:%d" (int .Values.app_engine.registry.nodePort)) }}
  SCHEDULER_USE_HOST_NETWORK: "false"
  SCHEDULER_RUN_MODE: "cluster"
  SCHEDULER_TASKS_NAMESPACE: {{ include "cytomine.appEngineTasksNamespace" . }}
