package be.cytomine.controller.error;

public enum ErrorCode {
    CORE_IAM_NOT_REACHABLE,
    CORE_REALM_NOT_FOUND,
    CORE_ACCOUNT_ALREADY_EXISTS,
    CORE_ROLES_NOT_ASSIGNED_TO_ACCOUNT,
    CORE_INVALID_CLIENT,
    CORE_INVALID_ROLES,
    CORE_IAM_UNKNOWN_CREATE_ERROR,
    CORE_IAM_UNKNOWN_DELETE_ERROR,
    CORE_IAM_UNKNOWN_UPDATE_ERROR,
    CORE_USERNAME_UPDATE_NOT_ALLOWED,
    CORE_INVALID_REFERENCE,
    CORE_IVALID_ACCOUNT,
    CORE_INVALID_ACCOUNT,
    CORE_CUSTOM_ATTRIBUTES_NOT_SET,
    CORE_ACCOUNT_NOT_FOUND
}
