apiVersion: v1
kind: Pod
metadata:
  name: export-test-results
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 20000
    runAsGroup: 20000
    fsGroup: 20000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: exporter
    image: registry.cytomine.org/docker/library/alpine:3.18
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 20000
      runAsGroup: 20000
      capabilities:
        drop: ["ALL"]
    volumeMounts:
    - name: test-reports
      mountPath: /reports
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: test-reports
    persistentVolumeClaim:
      claimName: e2e-test-reports
  - name: tmp
    emptyDir: {}
  restartPolicy: Never
