name: Build and Push Docker images

on:
  pull_request:
    branches:
      - main # to remove
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build-core:
    defaults:
      run:
        working-directory: ./core

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK ${{ vars.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ vars.JAVA_DIST }}
        java-version: ${{ vars.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ vars.GRADLE_VERSION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build
      run: gradle build -xtest --no-daemon


    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./core
        file: ./core/Dockerfile
        push: true
        tags: cytomine/core
        labels: latest

  build-pims:
    if: false #wait for https://github.com/cytomine/cytomine/pull/49
    defaults:
      run:
        working-directory: ./pims
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: build docker
      run: docker build . -t pims
