name: CBIR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./cbir

# Hardcoded for compatibility
env:
  PYTHON_VERSION: "3.10"

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Lint
        run: uv run ruff check

  type-check:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Type check
        run: uv run mypy cbir tests

  test:
    runs-on: self-hosted

    services:
      redis:
        image: registry.cytomine.org/docker/redis:${{ vars.REDIS_VERSION }}
        ports:
          - 6379:6379

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Run tests
        run: uv run pytest
        env:
          DATA_PATH: ./
          WEIGHTS: ./weights/resnet
