name: Code Quality

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  check-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r clients/python/requirements.txt
          pip install pylint pytest

      - name: Check lint
        run: pylint --output=lint.txt clients/python/cytomine clients/python/tests

      - name: Upload lint report
        if: ${{ always() }}
        run: |
          echo '# Lint report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat lint.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  check-type:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r clients/python/requirements.txt
          pip install "mypy[reports]" pytest

      - name: Check type
        run: >-
          mypy
          --disallow-incomplete-defs
          --disallow-untyped-calls
          --disallow-untyped-defs
          --ignore-missing-imports
          --txt-report ./
          clients/python/cytomine clients/python/tests

      - name: Upload type check coverage report
        if: ${{ always() }}
        run: |
          echo '# Type check coverage report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat index.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
