name: Code Quality

on:
  workflow_call:

jobs:
  python-lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Lint
        run: uvx ruff check .

  python-type-check:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Type check
        run: |
          uvx mypy cbir
          uvx mypy clients/python/cytomine clients/python/tests
          uvx mypy sam
