name: Code Quality

on:
  workflow_call:

jobs:
  java-lint:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v6.0.2

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Check lint
        run: gradle checkstyleMain --no-daemon --parallel

      - name: Upload lint reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: lint-report
          path: |
            app-engine/build/reports/checkstyle
            common/build/reports/checkstyle
            core/build/reports/checkstyle
            e2e-tests/build/reports/checkstyle
            registry-client/build/reports/checkstyle
            repository/build/reports/checkstyle
          retention-days: 7

  python-lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Lint
        run: uvx ruff check .

  python-type-check:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Type check
        run: |
          uvx mypy cbir
          uvx mypy clients/python/cytomine clients/python/tests
          uvx mypy sam
