name: Docker

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        image:
          - name: app-engine
            path: .
            dockerfile_path: app-engine
          - name: cbir
          - name: core
          - name: iam
          - name: nginx
          - name: pims
          - name: postgis
          - name: sam
          - name: web-ui
          - name: mongo
          - name: python-client
            path: clients/python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Cytomine registry
        uses: docker/login-action@v3
        with:
          registry: registry.cytomine.org
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image.path || matrix.image.name }}
          file: ./${{ matrix.image.dockerfile_path || matrix.image.path || matrix.image.name }}/Dockerfile
          push: true
          tags: cytomine/${{ matrix.image.name }}
          labels: latest
          allow: network.host
          network: host
