name: Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - "./docs/**"
  push:
    branches:
      - main
    paths:
      - "./docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./docs

jobs:
  build-docs:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Documentation
        run: npm run build

      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifacts
          path: src/.vuepress/dist/
          retention-days: 1

  deploy-docs:
    runs-on: self-hosted
    needs:
      - build-docs

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Download Docs Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-artifacts
          path: docs-artifacts

      - name: SSH deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          proxy_host: ${{ secrets.REMOTE_PROXY }}
          proxy_username: ${{ secrets.REMOTE_USER }}
          proxy_password: ${{ secrets.REMOTE_PASSWORD }}
          source: "src/.vuepress/dist/*"
          strip_components: 3
          target: ${{ secrets.TARGET_NEXT_PATH }}
