name: IMS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./pims

env:
  PYTHON_VERSION: "3.10"

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install --no-install-recommends --no-install-suggests \
            libopenslide-dev \
            libopenjp2-7-dev \
            libvips42 \
            libpng-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Run tests
        run: uv run pytest tests
        env:
          CONFIG_FILE: ./tests/pims-config.env
