---
name: IMS

on:
  workflow_call:
    secrets:
      PRIVATE_REPO_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v7.0.0

      - name: Set up the repository
        uses: actions/checkout@v7.0.0
        with:
          repository: imi-bigpicture/bigpicture-metadata-interface
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: imi-bigpicture

      - name: Load versions
        id: versions
        uses: ./.github/actions/load-versions

      - name: Install system dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install --no-install-recommends --no-install-suggests \
            libimage-exiftool-perl \
            libopenslide-dev \
            libopenjp2-7-dev \
            libvips42 \
            libpng-dev

      - name: Install GitHub CLI (gh)
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.PRIVATE_REPO_TOKEN }}" | gh auth login --with-token

      - name: Configure Git credential helper
        run: gh auth setup-git

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ steps.versions.outputs.python-version }}
          version: ${{ steps.versions.outputs.uv-version }}

      - name: Run tests
        run: uv --directory ./pims run pytest tests
        env:
          CONFIG_FILE: ./tests/pims-config.env
