name: IMS

on:
  pull_request:
    branches:
      - main
    paths:
      - "pims/**"
      - ".github/**"
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./pims

env:
  PYTHON_VERSION: "3.10"
  REPORT: test-report.xml

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install --no-install-recommends --no-install-suggests \
            libopenslide-dev \
            libopenjp2-7-dev \
            libvips42 \
            libpng-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir \
            gunicorn==22.0.0 \
            setuptools==80.9.0 \
            pytest \
            httpx \
            -r requirements.txt

      - name: Install plugins
        run: |
          python docker/plugins.py \
            --plugin_csv scripts/plugin-list.csv \
            --install_path plugins \
            --method install

      - name: Run tests
        run: pytest tests --junitxml=${{ env.REPORT }}
        env:
          CONFIG_FILE: ./tests/pims-config.env
