---
name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app-engine:
    uses: ./.github/workflows/app-engine.yaml
  cbir:
    uses: ./.github/workflows/cbir.yaml
  core:
    uses: ./.github/workflows/core.yaml
  ims:
    uses: ./.github/workflows/ims.yaml
  registry-client:
    uses: ./.github/workflows/registry-client.yaml
  sam:
    uses: ./.github/workflows/sam.yaml
  web-ui:
    uses: ./.github/workflows/web-ui.yaml
  repository:
    uses: ./.github/workflows/repository.yaml
  code-quality:
    uses: ./.github/workflows/code-quality.yaml

  docker-images:
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  helm-tests:
    needs:
      #- app-engine
      #- cbir
      #- core
      #- ims
      #- registry-client
      #- sam
      #- web-ui
      #- repository
      #- code-quality
      - docker-images
    uses: ./.github/workflows/helm-test.yaml
    secrets: inherit
