---
name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  app-engine:
    uses: ./.github/workflows/app-engine.yaml
  cbir:
    uses: ./.github/workflows/cbir.yaml
  ims:
    uses: ./.github/workflows/ims.yaml
  sam:
    uses: ./.github/workflows/sam.yaml
  web-ui:
    uses: ./.github/workflows/web-ui.yaml
  code-quality:
    uses: ./.github/workflows/code-quality.yaml
  test:
    uses: ./.github/workflows/test.yaml

  docker-images:
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  helm-tests:
    needs:
      - app-engine
      - cbir
      - ims
      - sam
      - web-ui
      - code-quality
      - test
      - docker-images
    uses: ./.github/workflows/helm-test.yaml
    secrets: inherit
