name: Quality

on:
  pull_request:
    branches:
      - master
    paths:
      - "cytomine-installer/**/*.py"
  push:
    branches:
      - master

jobs:
  lint-installer:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd cytomine-installer
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check lint
        run: |
          cd cytomine-installer
          pylint --output=lint.txt cytomine_installer tests

      - name: Upload lint report
        if: ${{ always() }}
        run: |
          echo '# Lint report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat cytomine-installer/lint.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
