name: SAM

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./sam

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Lint
        run: uv run ruff check

  type-check:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Type check
        run: uv run mypy app tests

  test:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Run tests
        run: uv run pytest
        env:
          CYTOMINE_HOST: "cytomine.host"
          CYTOMINE_PUBLIC_KEY: "public-key"
          CYTOMINE_PRIVATE_KEY: "private-key"
