name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - "core/src/main/resources/**"
      - "core/src/test/resources/**"
      - "core/src/**/*.java"
  push:
    branches:
      - master

jobs:
  test-core:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: cytomine/mongo:${{ vars.MONGO_VERSION }}
        env:
          MONGO_INITDB_DATABASE: cytomine
          MONGO_INITDB_ROOT_USERNAME: mongoadmin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017

      postgres:
        image: cytomine/postgis:${{ vars.POSTGIS_VERSION }}
        env:
          POSTGRES_NAME: docker
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Test core
        run: gradle :core:test --no-daemon

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: core/build/reports/
          retention-days: 7

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: core/build/test-results/
          retention-days: 7

      - name: Upload Java Code Coverage (JaCoCo)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: core/build/jacoco/
          retention-days: 7
