name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - "app-engine/src/main/resources/**"
      - "app-engine/src/test/resources/**"
      - "app-engine/src/**/*.java"
  push:
    branches:
      - master

jobs:
  ae-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Trigger unit tests
        run: gradle :app-engine:test --info --tests "be.cytomine.appengine.unit.*"

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: app-engine/build/reports/
          retention-days: 7
