name: Runner Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate-json-schema:
    runs-on: actions-runner-controller
    steps:
    - uses: actions/checkout@v4
