name: Test

on:
  workflow_call:

jobs:
  java-test:
    runs-on: self-hosted

    steps:
      - name: Set up the repository
        uses: actions/checkout@v6.0.2

      - name: Load versions
        id: versions
        uses: ./.github/actions/load-versions

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ steps.versions.outputs.java-distribution }}
          java-version: ${{ steps.versions.outputs.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: ${{ steps.versions.outputs.gradle-version }}

      - name: Run tests
        run: gradle test --no-daemon --parallel -x :e2e-tests:test
        env:
          TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX: registry.cytomine.org/docker/
          TESTCONTAINERS_RYUK_DISABLED: true

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: java-test-reports
          path: |
            app-engine/build/reports/
            core/build/reports/
            registry-client/build/reports/
            repository/build/reports/
          retention-days: 7
