name: Web UI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./web-ui

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Upload test coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: ./web-ui/coverage
          retention-days: 7

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v5
        with:
          name: test-report.html
          path: ./web-ui/reports/test-report.html
          retention-days: 7
