name: Web UI

on:
  pull_request:
    branches:
      - master
    # paths:
    #   - "web-ui/api-client/**/*.js"
    #   - "web-ui/api-client/**/*.vue"
    #   - "web-ui/ui/**/*.js"
    #   - "web-ui/ui/**/*.vue"
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./web-ui

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

  unit-tests:
    runs-on: self-hosted
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Upload test coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./ui/coverage
          retention-days: 7

      - name: Upload test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report.html
          path: ./ui/reports/test-report.html
          retention-days: 7
